#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config top_padding 0

# Rules
bspc rule -a Spotify desktop='^6'
bspc rule -a "Whatsapp-for-linux" desktop='^5'
bspc rule -a discord desktop='^5'
bspc rule -a obs desktop='^4'

# Border
bspc config focused_border_color        "#CC5555"
bspc config normal_border_color         "#5555AA"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
#picom -b
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

sleep 5
env LD_LIBRARY_PATH=/usr/bin/spotify LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify &
whatsapp-for-linux &
obs &

bspc config ignore_ewmh_focus true &&
discord &
sleep 10
bspc config ignore_ewmh_focus false
